[package]
name = "rust"
version = "0.1.0"
edition = "2018"

[dependencies]
ifaces = "0.1.0"
tempfile = "3.2"
zip = "0.5"
base64 = "0.13"
tiny_http = "0.7"
ipnet = "2.9.0"
net2 = "0.2.39"
interface = "0.0.1"
uuid = { version = "0.8.2", features = ["v4"] }
rand = "0.8.5"
walkdir = "2.5.0"
